server:
  port: 8072

spring:
  profiles:
    active: prod
  resources:
    static-locations: C:/upload/images
  mvc:
    static-path-pattern: /resources/**

mybatis:
  type-aliases-package: com.fanxl.admin.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true

logging:
  level:
    com:
      fanxl:
        admin:
          dao: DEBUG

# 文件上传地址路径
admin:
  fileUpload: C:/resources/