server:
  port: 8092

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    check-template-location: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: none
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  type-aliases-package: com.fanxl.admin.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


soft:
  security:
    browser:
      signInPage: /login
      signInResponseType: REDIRECT
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true

logging:
  level:
    com:
      fanxl:
        admin:
          dao: DEBUG

# 文件上传地址路径
admin:
  fileUpload: C:/resources/
